CREATE TABLE network (
	id INTEGER PRIMARY KEY,
	name TEXT NOT NULL
);
CREATE TABLE channel (
	id INTEGER PRIMARY KEY,
	name TEXT NOT NULL,
	network_id INTEGER NOT NULL
);
CREATE TABLE url (
	id INTEGER PRIMARY KEY,
	title TEXT NOT NULL,
	url TEXT NOT NULL,
	SOURCE TEXT NOT NULL,
	channel_id INTEGER NOT NULL,
	timestamp INTEGER NOT NULL
);